### ISSUE TITLE
PyDodge and Chatbox | Request

### ISSUE THREAD

**Issue by Rockpods** [QuiteAFancyEmerald/InvisiProxy#1]
I would like it if PyDodge could be added and possibly a chatbox, like the one on SystemYa.

(Originally, this issue asked about the inclusion PHP Proxy)

**Comment by QuiteAFancyEmerald** [comment]
Oh! I'm actually planning on adding a Chatbox to Holy Unblocker soon. I don't know about PHP Proxy, its not really the best anymore. But I can do PyDodge if you want.

But I will at some point:
- Add a working Chatbox
- Add PyDodge and more proxies in the future

:)

**Comment by Rockpods** [comment]
> Oh! I'm actually planning on adding a Chatbox to Holy Unblocker soon. I don't know about PHP Proxy, its not really the best anymore. But I can do PyDodge if you want.
> 
> But I will at some point:
> 
> * Add a working Chatbox
> * Add PyDodge and more proxies in the future
> 
> :)

Thank you

**Comment by QuiteAFancyEmerald** [comment]
If you join Titanium Network's Discord you can get access to an updated proxy list of both TN sites and Holy Unblocker, which may be unblocked in your district.

**Comment by QuiteAFancyEmerald** [comment]
PyDodge has been added. Chatbox will be done soon.

**Comment by easella** [comment]
anyone have any more sysya links?
https://schooltips.ml/ is down right now
![image](https://user-images.githubusercontent.com/74786054/115795236-874b8b00-a39d-11eb-9b63-a931f5200561.png)

my school blocked all the holy unblocker sites, sys32.dev,and phoenix-le.cf
