### ISSUE TITLE
Subdomains doesnt work

### ISSUE THREAD

**Issue by rsoorajs** [QuiteAFancyEmerald/InvisiProxy#10]
http://thisisatestdemo.tk/

The main website works.but when it goes to

https://cdn.thisisatestdemo.tk/google.com

it will not works..can you please check where the error lies ?

my heroku app domain is https://fhdugersru8googtsv43gsubaifivf.herokuapp.com/

![IMG_20210104_221358_835](https://user-images.githubusercontent.com/20116017/103558107-2d03e880-4eda-11eb-94e7-6b21e1435e9b.jpg)
![IMG_20210104_221401_288](https://user-images.githubusercontent.com/20116017/103558126-32613300-4eda-11eb-8b5d-bb2fed027596.jpg)

**Comment by QuiteAFancyEmerald** [comment]
Subdomains should work lol you probably just have it setup wrong. 

You seem to have the record setup correctly on Cloudflare but make sure you do the stuff below. I would also maybe force HTTPS and have SSL set to flexible.

Have you added both `cdn.thisisatestdemo.tk`, `www.thisisatestdemo.tk` and `thisisatestdemo.tk` to your Heroku app? Both would provide separate CNAME records which you would need to use through Cloudflare however once you add the domains to your Heroku app you can just use one record (from one of the three above) and use it as a CNAME value on Cloudflare for www, cdn and @. 

Second of all `cdn.thisisatestdemo.tk/google.com` is not a proper path for Alloy proxy unless you are like using some other proxy hosted on another instance.

Hopefully this helps. :)

**Comment by rsoorajs** [comment]
I am using via unblocker,i did the exact step which you mentioned.i am attaching the screenshots below and tell me where i am wrong

![IMG_20210104_232245_428](https://user-images.githubusercontent.com/20116017/103565156-d3a1b680-4ee5-11eb-95cf-d5e69dce947a.jpg)
![IMG_20210104_232238_299](https://user-images.githubusercontent.com/20116017/103565165-d7353d80-4ee5-11eb-93bc-21b55c688c73.jpg)
![IMG_20210104_232241_232](https://user-images.githubusercontent.com/20116017/103565171-da302e00-4ee5-11eb-8416-18907dd83bba.jpg)

**Comment by QuiteAFancyEmerald** [comment]
Are you sure you are using Via Unblocker? All the subdomains just link to the same Holy Unblocker instance.

Via Unblocker isn't like hosted locally on Holy Unblocker. You need another instance for that and you would just add that as a subdomain to your site. 

You would then edit `/expr/surf.js` as needed to navigate to it.

Do you need the Via Unblocker repository by chance, one that works with Heroku?

**Comment by rsoorajs** [comment]
> Are you sure you are using Via Unblocker? All the subdomains just link to the same Holy Unblocker instance.
> 
> Via Unblocker isn't like hosted locally on Holy Unblocker. You need another instance for that and you would just add that as a subdomain to your site.
> 
> You would then edit `/expr/surf.js` as needed to navigate to it.
> 
> Do you need the Via Unblocker repository by chance, one that works with Heroku?

`yeah i need the via unblocker repository.that will be very helpful.`

also please add support for https://uffizzi.com/

a free hosting site with lots of features like..free ssll..app never sleeps etc..

**Comment by rsoorajs** [comment]
> Are you sure you are using Via Unblocker? All the subdomains just link to the same Holy Unblocker instance.
> 
> Via Unblocker isn't like hosted locally on Holy Unblocker. You need another instance for that and you would just add that as a subdomain to your site.
> 
> You would then edit `/expr/surf.js` as needed to navigate to it.
> 
> Do you need the Via Unblocker repository by chance, one that works with Heroku?

so you create another app for via unblocker on heroku and set its domain like https://cdn.holyubofficial.net   on heroku and cloudflare.right ? wow cool...i dockerise the code,but aslike i said,people get confused on the subdomains part.else you have to mention the repos which we have to run seperately..

can you give the via unvlocker repo ?

**Comment by QuiteAFancyEmerald** [comment]
Here is the official Via repository: https://github.com/hypothesis/via

And here is one that works on Heroku: https://github.com/BinBashBanana/PyDodge
