### ISSUE TITLE
Discord Token Login -- PM Issue

### ISSUE THREAD

**Issue by Dark-Hackerr** [QuiteAFancyEmerald/InvisiProxy#11]
alright so i'm a big fan of what you have done here but i'm running into an issue 1 people get stuck in certain situations and just want to use discord and all they got is a school laptop running a token generator and the repl.it holy unblocker kills my bandwidth
2 alt addresses easily accessible like on a google docs or something
and i would love to know if you could teach me some stuff thank you very much

**Comment by QuiteAFancyEmerald** [comment]
Having a hard time trying to take that all in, no offense lol

Could you maybe explain more clearly? Regardless I'm going to try to interpret it. :) 

**"just want to use discord and all they got is a school laptop running a token generator":**

Not to state the obvious but make sure that a previously existing Discord account exists and then you would need to obtain the Discord token for that account manually on a separate device. You could also maybe try to find an online VM of some sort (not secure) just to obtain your Discord token. There are decent YouTube tutorials for this.

Also remember that QR login is supported. The Chatbox and the FAQ page linked on Holy Unblocker provide more feedback on this.

**"the repl.it holy unblocker kills my bandwidth 2 alt addresses easily accessible like on a google docs or something":**

I'm not sure about your current provider. From my experience __Repl_.it_ isn't the greatest for hosting regardless from my experience so I would switch to something like _Heroku_ or even _Glitch_ for free providers. I also heard that _Vercel_ is okay.

**Comment by QuiteAFancyEmerald** [comment]
Hmm well you could try using some of the official sites also.

**I can provide one for you:**
https://precede.design

Like it says on the site you can also join the Titanium Network Discord for more private site links which are restocked often.

Here is the TN Discord link: https://discord.com/invite/Dw6C7p5

**"discord token generator"**
Still not sure if you understand the concept but if you can't access devtools to obtain your discord token for your discord account then rip unless you can login via QR code. (Extended Information on the FAQ page)

But I did notice you said this:

**"now i have been doing research and there are pretty good emulators out there but i can only use it for a limited while technology"**

You could just obtain your Discord token through an online emulator/VM.

https://repl.it/@Evanlicious/Chromium-Browser

Or maybe something like Onworks, but note that this would not be secure at all.

I also just realized that your are trying to use Token login on your own instance from this repository. Make sure you are using Powermouse for that as its used with Holy Unblocker for Token login. 

But you can just use one of the official Holy Unblocker sites.

**Comment by Dj-Dark-Fox** [comment]
aye its me dj dark fox long story but i am so fucking close to actually getting ther i have my token i can open discord i got everything i need right?
except im running into an issue im using https://c.precede.design/studyflow/https://_ZGlzY29yZC5jb20=_/login?redirect_to=%2Fchannels%2F%40me
and when i try and lag in in using my token it redirects me to the log in page but this time theres no log in with token button could you please help me im also getting my persanol laptop today

**Comment by Dj-Dark-Fox** [comment]
if you could email me please do my new email is dj-dark-fox@outlook.com

**Comment by Dj-Dark-Fox** [comment]
![image](https://user-images.githubusercontent.com/77073235/103809082-fdaec200-5026-11eb-8957-92665d7b1777.png)

**Comment by QuiteAFancyEmerald** [comment]
Try going to https://c.precede.design/studyflow/https://_ZGlzY29yZC5jb20=_/app or reloading.

You should be logged in.

**Comment by Dj-Dark-Fox** [comment]
didnt work my school blocks cookies and site data so discord cant store my info

**Comment by Dj-Dark-Fox** [comment]
they also are up my asss
so i got my personal laptop today
i also cant sign i with google on this laptop (schools doing)
i cant allow notifications
i cant get extensions
im not even supposed to add an email but i figured out how this school is the worst damn school ever lol

**Comment by QuiteAFancyEmerald** [comment]
Looks like the issue you are having is an actual issue with Powermouse. I think just wait a bit until Divide (maintainer of Powermouse) fixes the issue.

lol hopefully this helps a bit tho
sorry for the wait

**Comment by QuiteAFancyEmerald** [comment]
I'll leave this open for a bit and will mention you again as soon as its updated.

**Comment by Dj-Dark-Fox** [comment]
ahh no its fine lol I just got my personal laptop.

I do have a request if you could email me and teach me some stuff I would love that I'm 15 I have made some coded material (cutt.ly/D-js) but it's all html I tried code .org but I would love to learn from a professional I understand if you don't have the time (all my dev friends don't lol) but I actually want to be able to do stuff with my knowledge base of code and if I learn more I could help people like you did
dj-dark-fox@outlook.com is my email just please consider it

_________________________
Sent form izac's personal email
________________________________

**Comment by QuiteAFancyEmerald** [comment]
I'm not sure... I'm not really great for tutorials lol

By the way try maybe logging in now via Token Login. Not sure if the issue has been fixed but some updates were made.

sorry about that tho :(

**Comment by Dj-Dark-Fox** [comment]
it is all right thanks though if there's any new inf just lemme know
________________________________

**Comment by Dj-Dark-Fox** [comment]
XD I DID IT

_________________________
Sent form izac's personal email
________________________________

**Comment by QuiteAFancyEmerald** [comment]
Pog epic! :D 

Glad this got sorted out. I'm going to close this issue just because it has been resolved.
