### ISSUE TITLE
NDS emulator support with webretro?

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/InvisiProxy#119]
If you go into my profile and into my random crap repository you will see that i have super mario galaxy DS rom i and really want to play it.Any chance you can tell me when is is coming.

**Comment by vackyton** [comment]
btw look at this .this is because 1 closed comment was a gold mine
![LMAO](https://user-images.githubusercontent.com/79385929/117985226-83f55080-b306-11eb-8bf2-2e3b1aabf459.png)

**Comment by QuiteAFancyEmerald** [comment]
Gold mine for getting Holy Unblocker sites blocked faster... also I'll look into this.

**Comment by vackyton** [comment]
thanks

**Comment by BinBashBanana** [comment]
I am working on fixing the Nintendo 64 emulator and adding the DS emulator. Updates will be posted [here](https://github.com/BinBashBanana/webretro).

**Comment by BinBashBanana** [comment]
Also, PS1 should be coming as well.

**Comment by vackyton** [comment]
BinBashBanana your a legend try my super mario galaxy rom on it plz it is on my repository named random crap

**Comment by BinBashBanana** [comment]
I'm already using NSMB and SM64 DS to test it.

**Comment by vackyton** [comment]
hey could i get the demo if that is ok?

**Comment by BinBashBanana** [comment]
There is no demo yet.

**Comment by vackyton** [comment]
Then how are you testing sm64ds?

**Comment by QuiteAFancyEmerald** [comment]
Just be patient lol

**Comment by BinBashBanana** [comment]
Hey uh, to be honest, the DS cores that currently work on retroarch (Desmume and MelonDS) aren't actually that optimized as of right now, so they will be laggy in a browser, so I will wait until one is more optimized (preferably desmume) before I compile it.

**Comment by vackyton** [comment]
ok nice....

**Comment by vackyton** [comment]
btw @QuiteAFancyEmerald did you come back from your break

**Comment by vackyton** [comment]
how is the ds emulator working rn?

**Comment by obscurerev** [comment]
don't know if a manual ds emulator on the web is even possible.

**Comment by BinBashBanana** [comment]
@obscurerev it's retroarch ported to webassembly with emscripten

@vackyton chill out man

**Comment by vackyton** [comment]
@BinBashBanana I just wanted to know the process

**Comment by BinBashBanana** [comment]
I'm not working on it right now. I'm not the one doing the core optimizations for retroarch.

**Comment by easella** [comment]
Hey everyone I made a service(https://historybooks.awdrgyjil1234.repl.co) that has a bunch of holyunblocker urls, Lucridious Official(very similar to holy unblocker, has womginx, alloy, and pydodge) urls, systemya urls, nodeunblocker urls, and alloyproxy urls! It has a password. Contact me at my email easella@yahoo.com and I will tell you the password.

**Comment by BinBashBanana** [comment]
@easella it was incredibly easy to find the password, and even if it wasn't, I'm pretty sure that kind of thing would not be allowed here.

**Comment by easella** [comment]
Hey everyone I made a service(https://historybooks.awdrgyjil1234.repl.co) that has a bunch of holyunblocker urls, Lucridious Official(very similar to holy unblocker, has womginx, alloy, and pydodge) urls, systemya urls, nodeunblocker urls, and alloyproxy urls! It has a password. Contact me at my email easella@yahoo.com and I will tell you the password.

**Comment by BinBashBanana** [comment]
Do not repost that again.

**Comment by easella** [comment]
but it has a password

**Comment by easella** [comment]
im sorry.ill delete all my posts

**Comment by vackyton** [comment]
Yo,Any updates?

**Comment by vackyton** [comment]
@BinBashBanana

**Comment by obscurerev** [comment]
update?

**Comment by BinBashBanana** [comment]
no updates

**Comment by vackyton** [comment]
xD :sad face:

**Comment by obscurerev** [comment]
it will probably not happen anytime soon

**Comment by vackyton** [comment]
@QuiteAFancyEmerald I have a question, could make a in-depth explanation on how proxys work?

**Comment by SubduedCyns** [comment]
any Updates?

**Comment by QuiteAFancyEmerald** [comment]
Both have been added
