### ISSUE TITLE
Discord Proxy Information and Support

### ISSUE THREAD

**Issue by Tay02932** [QuiteAFancyEmerald/InvisiProxy#12]
Discord won’t long and Human verification won’t load

**Comment by QuiteAFancyEmerald** [comment]
Hi! Well once again captcha isn't support on any of the proxies. 

However Discord support does exist. Make sure you are NOT logging in normally.

Try reading the FAQ page on the official Holy Unblocker sites or #faq on the Chatbox.

**General Simplified Steps:**
- Go to either Surf Freely/Web Proxies or Discord (HU exclusive) from the navbar of the site you are on.
- Select either Alloy Proxy or AP.
- Type out one of these terms:
```
https://discord.com/login
https://discord.com/app
https://discord.com/
```
- Then hit either Stealth or Classic on Holy Unblocker sites.

It will be rather self-explanatory.
Alloy works for only QR code logins.
QR Logins on Alloy will require a mobile device.

**QR Login:**
Make sure you are using Alloy + QR Code for Discord.
QR Code Information: https://support.discord.com/hc/en-us/articles/360039213771-QR-Code-Login-FAQ
Use the above through one of the proxies to read if you can't. ^^

If the page appears gray on the first load, reload/spam reload the page a bunch.
If the QR code doesn't load, reload/spam reload the page a bunch.
If the page/discord logo keeps loading, reload/spam the page also. 

You may also right-click the page and do "Reload Frame" to reload also. ^^^

PM also has amazing support for QR logins. Feel free to mess around between PM and Alloy.

**Token Login:**
Also, search up on YT on How to find your Discord Token when using Token Login.

If the page appears gray on the first load, reload/spam reload the page a bunch.

This only works on Powermouse but not the best option.
Token logins on Powermouse (PM Proxy) will require another device also for recovering your Discord Token.

**YOU CANNOT LOGIN NORMALLY. READ THE ABOVE. QR AND TOKEN LOGIN ONLY.**
