### ISSUE TITLE
Full version of minecraft

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#131]
Add it or I will get you in a lawsuit

**Comment by Brady-Shike** [comment]
You've left me with only one option

**Comment by Brady-Shike** [comment]
Have fun in court

**Comment by vackyton** [comment]
lmaoooooooo

**Comment by the-skiddo** [comment]
lmao how can a 10-year-old file a lawsuit for not recreating a full-on game in javascript, the creator of this awesome service makes websites to link together brilliant proxies and HTML games, don't waste his time on this stuff lol

**Comment by Brady-Shike** [comment]
you have illegal mario on your site and I will report it to nintendo, also
I am 12

**Comment by the-skiddo** [comment]
Honestly kid, it doesn't surprise me. Besides, what does a 12 year old have a way of reporting this to Nintendo lmao. Go find and bug some other place to "report" and "file lawsuits", but don't do it here.

**Comment by Brady-Shike** [comment]
There is a report button on nintendo.com

**Comment by the-skiddo** [comment]
Kid, I said please go bug some other place about this. Also, with the magic of simply a new domain, even if you report goes through and they SOMEHOW get the site taken down, they still have the source code, so this stays up no matter what happens.

**Comment by QuiteAFancyEmerald** [comment]
@Brady-Shike Please read #57. Your request is completely unreasonable and not really possible lol sorry

You could try using something like [](https://remote-play.dixper.gg/rooms) (if not blocked, remote desktop service)

**Comment by vackyton** [comment]
does he know if you use your own textures you can get can't copyrighted and can't sue lmaooo

**Comment by vackyton** [comment]
Maybe lil 10 yr old can play minecraft education edition:)

**Comment by the-skiddo** [comment]
very funny
