### ISSUE TITLE
How exactly does Arc work?

### ISSUE THREAD

**Issue by SkidFace** [QuiteAFancyEmerald/InvisiProxy#134]
I'm just curious, from what I understand it uses other machines nearby yours to speed up loading so not everyone has to connect to a faraway server. So, for example, one student of a school enables it, and all others connected to the same network get faster loading times? Do I have it correct? Thanks!

**Comment by Nebelung-Dev** [comment]
https://arc.io/about/

**Comment by the-skiddo** [comment]
Ah, I see. Thank you!
