### ISSUE TITLE
How do you use emulators

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#136]
I want to know

**Comment by BinBashBanana** [comment]
(How to use the emulators: go find a rom for a game on a rom site, which you can google, and download the rom. Then go to the respective emulator (NES for NES roms, GBA for GBA roms, etc.) Then press the choose file button, or drag the file into the page. It is suggested that you unzip the file if it is a zip file, but you do not have to.)
