### ISSUE TITLE
Any Spotify login support?

### ISSUE THREAD

**Issue by obscurerev** [QuiteAFancyEmerald/InvisiProxy#141]
I've tried all of the proxy's in the official holy unblocker for open.spotify.com but none of them work. Maybe the Molten Proxy might support it?

**Comment by QuiteAFancyEmerald** [comment]
Molten Proxy right now is kinda at a halt sadly but maybe. But yeah sadly Spotify is not supported on any of the proxies. :(

**Comment by easella** [comment]
Molten was abndoned
