### ISSUE TITLE
Can you add The first 2 levels of minecraft dungeons

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#145]
plz

**Comment by the-skiddo** [comment]
My man, MCD is a professional game by professional game devs. Not everything can be magically added online. The dev of this website makes a very, very convenient way to access proxies and pre-made games- he doesn't make the games, let alone something that's very hard to recreate. 

One more thing- this post was made by the same person who threatened to file a lawsuit for "illegal mario on your site". How is this any different? Somebody could easily say to **you** "oMg He WaNtS iLleGaL McD!!!"
![image](https://user-images.githubusercontent.com/74504657/120520672-ef23c700-c388-11eb-9835-366e224a5737.png)


Please man, stop asking for impossible "requests" and at the very least be consistent. Thanks.
