### ISSUE TITLE
Game Request: Minecraft / WebCraft

### ISSUE THREAD

**Issue by Kore-Development** [QuiteAFancyEmerald/InvisiProxy#151]
https://minecraft1.glitch.me/
This would either replace or be in addition to the Minecraft already available. It has functional multiplayer and the multiplayer world is stored, so you can use it later. This version of WebCraft is my fork of https://github.com/Overv/WebCraft. The only limitation is that it needs to be run using Node.js, but you could probably put it on m.example.com and have the HTML5 game page link to that. If this should be added, I could make a pull request.

**Comment by QuiteAFancyEmerald** [comment]
Perhaps :D

**Comment by QuiteAFancyEmerald** [comment]
Better alternative existing
