### ISSUE TITLE
Session Cookie implementation

### ISSUE THREAD

**Issue by arunprasath-dev** [QuiteAFancyEmerald/InvisiProxy#152]
How do I add a bot protection like below that works with the subdomains like (cdn.holyubofficial.net)

![image](https://user-images.githubusercontent.com/9743538/123538156-091ab480-d751-11eb-941a-a5b762a6841d.png)

I understand that it works based on session cookie, can you please help me with an example to implement this.

Thanks.

**Comment by easella** [comment]
f

**Comment by easella** [comment]
here is an example in php:
https://replit.com/@awdrgyjil1234/HardtofindUtterQuotes#index.php

**Comment by QuiteAFancyEmerald** [comment]
@wapfalls What web server are you using? Huge sorry for the delay

**Comment by arunprasath-dev** [comment]
> @wapfalls What web server are you using? Huge sorry for the delay

Am using Nginx

**Comment by QuiteAFancyEmerald** [comment]
Perfect :D

You can either use a map directive or merely add this under a location block.
```nginx
location / {
      ...
      
      # Cookie Authentication
      if ($http_cookie !~* '__cor_auth=1') {
          return 401;
      }
  }
  ```
  
  Lastly if you wish to go further you may also ratelimit any malicious or unwanted user agents using this:
  https://stackoverflow.com/questions/19337662/blocking-all-bots-except-a-few-with-nginx/24820722#24820722
  
  Credits to Divide and Duce for this.

**Comment by vackyton** [comment]
why is dis still open?

**Comment by arunprasath-dev** [comment]
@QuiteAFancyEmerald Thank you so much for the response. I will give it a try! :)
