### ISSUE TITLE
Sysya is down

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/InvisiProxy#154]
https://user-images.githubusercontent.com/79385929/124686229-b5227500-dea0-11eb-96fa-05d74c564914.mp4

here's proof

**Comment by QuiteAFancyEmerald** [comment]
Sorry about that. Please note my summer announcement regarding Holy Unblocker:

> Just an update regarding Holy Unblocker over the summer:

> Some users may have noticed that the official sites have been having more issues lately and that sites have not been restocked as frequently as during the school year. Primarily this is because I am focusing on other projects over the summer. However, this does not mean that Holy Unblocker will not be updated but simply the official sites will not be maintained as often compared to usual.
 
> Sorry for any issues this causes. Expect normal behavior to resume during mid-August. Have epic things planned >:D

**Comment by vackyton** [comment]
Np

**Comment by the-skiddo** [comment]
Sounds good

**Comment by vackyton** [comment]
Also after your done with the break u deserved can u add fnf here's the link for it to run online snipergaming888.github.io

github.com/snipergaming888/snipergaming888.github.io

I have made my own fnf mod site but i am gonna make things custom

Vackyton.github.io/BiggerFNFAttempt

Pls add it it is really ez

**Comment by easella** [comment]
lol.
thats not even sysya

**Comment by vackyton** [comment]
I know but the other proxies worked so I thought the servers of sysya were down and what was the problem then
