### ISSUE TITLE
Repl.it w/ Holy Unblocker

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/InvisiProxy#156]
Well title says it all update the replit please.

**Comment by vackyton** [comment]
Also some reason like half of the things don't work xD

**Comment by vackyton** [comment]
On repl.it ofc

**Comment by QuiteAFancyEmerald** [comment]
Are you using the mini-button on the README? If so please make sure you are doing everything setup related correctly and make sure Node.js/Express is selected for your environment. To be completely honest I don't really use Repl but it was working perfectly fine with Holy Unblocker when I tested it. 

Provided Setup Details:
```
npm install
npm start
```

Pretty much it :D

**Comment by vackyton** [comment]
so wait i use node.js? cause i thought it works with python xD
and yes i know about the npm

**Comment by vackyton** [comment]
and there is no pydodge proxy

**Comment by vackyton** [comment]
![Screenshot 2021-07-23 11 04 50 PM](https://user-images.githubusercontent.com/79385929/126855708-167373f9-a60d-4428-a372-5551a1acf2d6.png)

**Comment by vackyton** [comment]
see this is what happens when i try to go this link
https://fnf.run3.io/camellia/1.25/

**Comment by vackyton** [comment]
that screenshot is from node.js language not the python one

**Comment by vackyton** [comment]
heres the site btw https://holyunblockerpublic.vackyton.repl.co/ (node.js one)
https://HolyUnblockerPublic-1.vackyton.repl.co (python one)

**Comment by vackyton** [comment]
and only alloy works on both sites
via file is missing it says (will check if via file is there later)
sysya and womginx says there's a typo

**Comment by vackyton** [comment]
only sysya works on this site
https://kbhgames.com/game/friday-night-funkin-vs-camellia
and i want to play it but the real ones(made by u guys) sysya isn't going to work until summer ends

**Comment by easella** [comment]
Hey everyone I made a service(https://historybooks.awdrgyjil1234.repl.co) that has a bunch of holyunblocker urls, systemya urls, nodeunblocker urls, and alloyproxy urls! It has a password. Contact me at my email easella@yahoo.com and I will tell you the password.

**Comment by easella** [comment]
ok

**Comment by vackyton** [comment]
i suggest making like the thing i circled then inside it fill it with like 5000 lines and 1 line contains the actual code that should work i guess
![Screenshot 2021-07-29 10 32 44 PM](https://user-images.githubusercontent.com/79385929/127591254-93ae7ee4-4d4c-4dff-ac52-2e1b546bf462.jpg)

**Comment by QuiteAFancyEmerald** [comment]
Uhh only Alloy Proxy is hosted locally. Please make sure you are setting up any external proxies correctly. (More information in the README)

**Comment by vackyton** [comment]
k
