### ISSUE TITLE
all sites are completely down

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/InvisiProxy#157]
![image](https://user-images.githubusercontent.com/74786054/126685223-b43d204c-1480-44e0-b4d3-09aadbf2492b.png)

i refreshed and it still doesnt work

**Comment by obscurerev** [comment]
yeah, me too. They might be down for maintenance so they may be back up shortly.

**Comment by QuiteAFancyEmerald** [comment]
Issue is now resolved sorry.

**Comment by easella** [comment]
ok. fix sysytemya please.
