### ISSUE TITLE
Regarding the downtime for Holy Unblocker - Please read before opening an issue (ETA August 8th)

### ISSUE THREAD

**Issue by 6829ASCS** [QuiteAFancyEmerald/InvisiProxy#158]
It seem that all the proxies on the HU sites are not functioning at all, atleast for me. This happened right after the Corrosion Proxy was added. Can someone confirm if this is an issue with the site from **MY** end or it's an issue with all HU mirror websites. The other mirror links, such as Incognito or Resilience seem to be working though.

Edit: I tried the tips on the FAQ page and nothing seemed to solve either the 404 error screen or the other screen I received whenever I attempted to use one of the proxies. Find below screenshots of both screens mentioned.

![Screenshot 2021-08-05 20 49 40](https://user-images.githubusercontent.com/88504752/128390191-c764340e-c971-4325-97a9-6f853f0caf00.png)

![Screenshot 2021-08-05 21 04 27](https://user-images.githubusercontent.com/88504752/128391679-49cd7b8a-598c-47bd-ac1f-a9962d9fd024.png)

**Comment by 6829ASCS** [comment]
The screenshots linked above is what appeared for me when I tried using the Alloy Proxy. Similar results when attempting to use Womginx, Corrosion and PyDodgeB.

@QuiteAFancyEmerald

**Comment by vackyton** [comment]
@6829ASCS  same for me only alloy worked but the other proxies didn't i think he said the answer in a closed issue

**Comment by vackyton** [comment]
@6829ASCS  found it https://github.com/titaniumnetwork-dev/Holy-Unblocker/issues/156

**Comment by QuiteAFancyEmerald** [comment]
Yeah uh this was mentioned on the Discord and can be found on the homepage.

A‭ll official H‌oly Unblocker proxy instances have be⁢en temporarily disab‌led du⁡e to le‌aks and ab⁪use. Normal activity will resume on August 8th.
Also yes on August 8th Corrosion will be usable on Holy Unblocker. Actually already have it setup but the events above have changed things :(
(special thanks to @LinuxTerm#4547 for that contribution)

Now time to state information for those who don't understand *why* leaking is harmful to TN. :oopidie: 
1) It gets sites blocked much faster 
2) It expends more money from the maintainer therefore less domains can be restocked monthly

Not leaking sites significantly helps TN remain stable when it comes to being able to obtain a domain from the proxy bot that is not blocked and while maintaining fast services. If you wish to support TN leaking sites does not help. Increased visibility is helpful but not leaking sites. >:(

**Comment by vackyton** [comment]
also if i can i will try to donate on oct <3

**Comment by obscurerev** [comment]
Here's a quick tip: do not bookmark a HU site or any other site that you don't want to get blocked. Your admin will see it and will eventually block it.

**Comment by 6829ASCS** [comment]
> Here's a quick tip: do not bookmark a HU site or any other site that you don't want to get blocked. Your admin will see it and will eventually block it.

Ah alright! My school is using Securely which recently blocked a huge amount of the HU mirror links. In such situations I can't get more as I don't have access to TitaniumNetwork's server as it's blocked.

**Comment by vackyton** [comment]
@6829ASCS I have tons of bookmarked sites but they don't get blocked 
Also my school uses something called Relay Classifier and Relay and it is not on web store
http://lsrelay-config-production.s3.amazonaws.com/522675c8e566c8eeb53a06be383e5a78f4460bd5d3e6f5b56e9c6ba2413722e5/block_screen.html?id=c8dfacb3-4d2b-4e01-a4a3-6981a86cb86b
here is 1 of the blocked links when i try to go on a blocked site

**Comment by QuiteAFancyEmerald** [comment]
It actually doesn't really depend on what filter your district uses. The actual scenario depends on whether or not your device is a Chromebook or managed by a Google Workspace device policy.

**Comment by obscurerev** [comment]
> > Here's a quick tip: do not bookmark a HU site or any other site that you don't want to get blocked. Your admin will see it and will eventually block it.
> 
> Ah alright! My school is using Securely which recently blocked a huge amount of the HU mirror links. In such situations I can't get more as I don't have access to TitaniumNetwork's server as it's blocked.

If you can't remember the link at some point just make a shortcut, they don't detect shortcuts on your taskbar where google chrome is. If you don't know how just go to the 3 lines on the top right corner, go to more options drop down and click create shortcut. I have always done this and the sites never get blocked.

**Comment by 6829ASCS** [comment]
> > > Here's a quick tip: do not bookmark a HU site or any other site that you don't want to get blocked. Your admin will see it and will eventually block it.
> > 
> > 
> > Ah alright! My school is using Securely which recently blocked a huge amount of the HU mirror links. In such situations I can't get more as I don't have access to TitaniumNetwork's server as it's blocked.
> 
> If you can't remember the link at some point just make a shortcut, they don't detect shortcuts on your taskbar where google chrome is. If you don't know how just go to the 3 lines on the top right corner, go to more options drop down and click create shortcut. I have always done this and the sites never get blocked.

Yeah I do that alot. I used google sites to make fake "apps" using the same mechanism Holy Unblocker sites use to change the logo of the site and name. Eh and I have a pretty much full folder of over 13 mirror links I'v obtained woo

![Screenshot 2021-08-08 06 53 01](https://user-images.githubusercontent.com/88504752/128619188-77ffab7a-ccaf-4845-978b-abc094bf7b7d.png)

**Comment by 6829ASCS** [comment]
Is the downtime over? It seems to still be going on. Just want to check if its an issue from my side or the downtime really is still going on..

**Comment by QuiteAFancyEmerald** [comment]
Quote from the Discord

> Holy Unblocker is officially back up with Corrosion featured as a proxy option. This means like sites such as YouTube and even Netflix are supported now with nearly full support on HU. If you get any errors within the next few hours or so simply clear your cache/do a hard reload. Lastly with Netflix or YouTube simply refresh the page in case of errors.

Sorry for the partial delay :D

**Comment by vackyton** [comment]
YOOOO thanks finally

**Comment by vackyton** [comment]
@QuiteAFancyEmerald 
![Screenshot 2021-08-08 8 36 04 PM](https://user-images.githubusercontent.com/79385929/128650622-1dcee830-a615-465c-84dd-f7490a5e016f.png)
still not
