### ISSUE TITLE
repl.it

### ISSUE THREAD

**Issue by Darker-Ink** [QuiteAFancyEmerald/InvisiProxy#20]
So How Do I do this for repl.it as I use that for most things but I can't get it to work on there can you help me with it?

**Comment by QuiteAFancyEmerald** [comment]
It should be basic setup (no offense) but here:
https://repl.it/github/QuiteAFancyEmerald/HolyUnblockerPublic

Try the link above or using the deploy button that I have added to the README. It will automatically setup a workspace for you. :)
Sorry though I am not one for like full on tutorials. I tried my best to explain everything in the README.

**Comment by Darker-Ink** [comment]
> It should be basic setup (no offense) but here:
> https://repl.it/github/QuiteAFancyEmerald/HolyUnblockerPublic
> 
> Try the link above or using the deploy button that I have added to the README. It will automatically setup a workspace for you. :)
> Sorry though I am not one for like full on tutorials. I tried my best to explain everything in the README.

I get this when I try starting it

node v12.16.1


Repl.it: Updating package configuration

--> npm install jquery opn ruffle-core cooljs
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ruffle-core - Not found
npm ERR! 404 
npm ERR! 404  'ruffle-core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-14T18_59_19_953Z-debug.log
exit status 1


Repl.it: Package operation failed.

**Comment by QuiteAFancyEmerald** [comment]
Are you using the latest version of Holy Unblocker? Also make sure you did everything correctly. Only do `npm install` not `npm install jquery opn ruffle-core cooljs` and try to do things manually with Repl. I think perhaps you must have somehow cloned a WIP version of Holy Unblocker early on when I was working on it since I was working on adding Ruffle back then.

I also just tried deploying to Repl.it myself and it works. :)

![image](https://user-images.githubusercontent.com/46467239/107888173-aae6e680-6ebf-11eb-8cf0-bcee6a92162c.png)

**Comment by Darker-Ink** [comment]
Oh No I see the problem I was using the master version as repl.it choses that I changed it to v4 and it works now!

**Comment by QuiteAFancyEmerald** [comment]
Wait um the master branch should work though. I meant that perhaps you were using an older version of the master branch. v4 is like months old lol and is incredibly outdated.

**Comment by Darker-Ink** [comment]
> Wait um the master branch should work though. I meant that perhaps you were using an older version of the master branch. v4 is like months old lol and is incredibly outdated.

if its fine with you can you give me the link of yours on repl.it so I can just fork it to use? If that is fine.... As I am using the link you gave and still can't get it working

**Comment by QuiteAFancyEmerald** [comment]
Yeah sure. But the deploy buttons should also work normally though oof.
https://repl.it/@Epicloudygamer/HolyUnblockerPublic-5

**Comment by Darker-Ink** [comment]
> Yeah sure. But the deploy buttons should also work normally though oof.
> https://repl.it/@Epicloudygamer/HolyUnblockerPublic-5

Thank you! I see my Mistake or something as when I run 
node app.js
it works so idk what is wrong but I guess I got it working thanks!

**Comment by vackyton** [comment]
change the language from bash to python cause that can be a problen too. since bash requires  main.sh
