### ISSUE TITLE
Extra characters in index.html

### ISSUE THREAD

**Issue by R-Josef** [QuiteAFancyEmerald/InvisiProxy#21]
https://github.com/QuiteAFancyEmerald/HolyUnblockerPublic/blob/ed9650b75784b73918c8dc57ee57a453bedb55dc/views/index.html#L53
I fount there are some unnecessary comment characters, it makes the homepage a bit weird.

**Comment by QuiteAFancyEmerald** [comment]
Oh thanks!
Whoops. Will remove this right now.
