### ISSUE TITLE
Web proxy cannot jump correctly

### ISSUE THREAD

**Issue by R-Josef** [QuiteAFancyEmerald/InvisiProxy#22]
I have a Holy Unblocker website and I found that the Alloy Proxy cannot redirect correctly in latest version.  
For example, my website address is holyub.myhost.com, and I enter the website "www.mcbbs.net" through the search box on the Alloy Proxy page "https://holyub.myhost.com/?a". Under normal circumstances, it should be redirected to "https://holyub.myhost.com/fetch/aHR0cHM6Ly93d3cubWNiYnMubmV0/", but now it has no response and it timed out after a long period of time, I tried to open this address directly and it can open normally.  
I also have Holy Unblocker running on another server, but it is an old version on commit: 4f05b2a95d14920915fd9d8450242191c8fe1fcc, it can be used normally, but when I updated it to the latest version, the same problem occurred.

**Comment by R-Josef** [comment]
Now i downgrade it to 4f05b2a95d14920915fd9d8450242191c8fe1fcc and it can open normally.

**Comment by QuiteAFancyEmerald** [comment]
Issue has been resolved. :)

**Comment by R-Josef** [comment]
Thank you. 👍

**Comment by QuiteAFancyEmerald** [comment]
Of course no problem. ;D
