### ISSUE TITLE
How to change default place for the proxy ?

### ISSUE THREAD

**Issue by masbenny** [QuiteAFancyEmerald/InvisiProxy#23]
Default directory proxy: `http://localhost:8080`
default config.json : 
`{
    "port": "8080"
}`

how to change to other directory ??
ex : `http://localhost/newdirectory/:8080`

i have problem cannot running proxy and get redirect on my homepage site: https://jejagu.com/HolyUnblockerPublic/views/

**Comment by QuiteAFancyEmerald** [comment]
What web server are you using? I'm kinda confused on what you are asking but if you are asking how to change the directory path for where static assets are served with Holy Unblocker in app.js you can look there. :)

On your web server you would want to have a location block of some sort for /whateverpathhere with Holy Unblocker as a backend, there should be no need for having to modify Holy Unblocker directly but I'm not sure how you have this set up. In fact if you did setup Holy Unblocker correctly you could simply have a path like so: `https://jejagu.com/whateverpathhere`

Something like `proxy_pass http://localhost:8080` (NGINX) or `ProxyPass /whateverpathhere http://localhost:8080/` (Apache).

Could you provide more information about what you are doing?

**Comment by masbenny** [comment]
i used Apache/2.4.41 (Ubuntu) Server. and default directory is : `/var/www/html/`

i am install like the recommendation how to setup.

I try to run the application in directory with `chmod 777` :  `https://jejagu.com/HolyUnblockerPublic/ `
i got message forbidden error,

Then i try run in directory ; `https://jejagu.com/HolyUnblockerPublic/views/ `
The app running, but cannot used proxy and get redirect to `https://jejagu.com/?z`


i try to change in `app.js` directory like this :
 `//Cloudflare Attack Mode Fix

app.post('/var/www/html/HolyUnblockerPublic/views/', async(req, res) => res.send(fs.readFileSync(path.join(__dirname, 'views', 'index.html'), 'utf8')));`


but still get redirect in `https://jejagu.com/?z`

i want the proxy can run at default directory : `https://jejagu.com/HolyUnblockerPublic/views/` or `https://jejagu.com/HolyUnblockerPublic`


i try other source code proxy : `https://jejagu.com/proxy/` with npm install has not problem.


Then i find **Holy Unblocker** with nice themes and more proxy really very cool... but still make me got headeache :D

**Comment by QuiteAFancyEmerald** [comment]
I'm not sure how you are setting this up. You are using npm or something like pm2 correct? If setup correctly, `https://jejagu.com/HolyUnblockerPublic/views` would simply be `https://jejagu.com/HolyUnblockerPublic/`. Same goes for on-site navigation.

#### Steps
Here is how I would interpret the correct steps for this. I would maybe use another folder for this but you can also clone Holy Unblocker in `/var/www/html/`.

Make sure you have Node.js installed.

```
$ cd /var/www/html
$ git clone https://github.com/QuiteAFancyEmerald/HolyUnblockerPublic.git
$ cd HolyUnblockerPublic
$ npm install
$ npm start
```

Then simply add this to `httpd.conf`:
```
ProxyPass /HolyUnblockerPublic http://localhost:8080/
```
Lastly be sure to have “mod_proxy” and “mod_proxy_http” modules enabled. Restart Apache and then try using Holy Unblocker. 

Tell me if the issues persist even after you do this.

**Comment by masbenny** [comment]
root@bugs12:/var/www/html/HolyUnblockerPublic# npm start

> holyub@4.5.0 start
> node app.js


**keep have the same problem....**
the proxy always redirect at this url : `https://jejagu.com/?z`

jejagu.com is main site.

i used proxy to other directory, the **result** will be like : `https://jejagu.com/HolyUnblockerPublic/?z`

**Comment by Susdevlmao** [comment]
Have u asked anyone else on this problem?

**Comment by vackyton** [comment]
so wait you want to change the link for ex instead of alloy being /a you want it to be /alloy correct?

**Comment by easella** [comment]
Hey everyone I made a service(https://historybooks.awdrgyjil1234.repl.co) that has a bunch of holyunblocker urls, Lucridious Official(very similar to holy unblocker, has womginx, alloy, and pydodge) urls, systemya urls, nodeunblocker urls, and alloyproxy urls! It has a password. Contact me at my email easella@yahoo.com and I will tell you the password.

**Comment by vackyton** [comment]
@easella  
![Screenshot 2021-07-29 10 27 54 PM](https://user-images.githubusercontent.com/79385929/127590730-b4c77033-f1d8-4cb9-a925-b9a1db8c2fdd.png)
lol i found it in the source code of the pag just press ctrl+u and scroll to the site lol

**Comment by vackyton** [comment]
@easella i suggest making the thing i circled (idk wut they are called a script?)      and fill it with like 5000 lines and 1 contains the code that makes the password screen
![Screenshot 2021-07-29 10 34 39 PM](https://user-images.githubusercontent.com/79385929/127591488-3cbef704-3ac1-4396-9164-1e29125ee53f.png)

**Comment by vackyton** [comment]
wrong image
this is the right 1
![Screenshot 2021-07-29 10 32 44 PM](https://user-images.githubusercontent.com/79385929/127591514-a2eae71e-7a93-4dbc-9c8b-6388def1629c.jpg)

**Comment by vackyton** [comment]
and i think u can just inspect element lol i am on a school chromebook rn so idk they disabled it on my chromebook xD

**Comment by QuiteAFancyEmerald** [comment]
I'm closing this since the above very much confused me and no response has been given in awhile. 
> "i used proxy to other directory, the result will be like : https://jejagu.com/HolyUnblockerPublic/?z"

Is the above implying that the steps above did work? If so then all you need to do is rename the folder for a new path and edit `httpd.conf` with something like so lol

```ProxyPass /newdir http://localhost:8080/```

Feel free to open this again if this still is an issue :D
