### ISSUE TITLE
Not an issue, but rather a suggestion

### ISSUE THREAD

**Issue by SkidFace** [QuiteAFancyEmerald/InvisiProxy#28]
Hey QuiteAFancyEmerald! Your code is awesome and I appreciate what you have done, although I do have one suggestion. Typically schools like to look through computer's search history, and configures the computer so that students cannot clear it. With that in mind, is there a way you could have the <title> tag display something like "google" so it won't draw suspicion as opposed to something like "Reddit" (which schools obviously would pick up on, since a lot of people look at the tab titles rather than the actual link at first glance) This probably isn't possible, but I really do appreciate you taking the time to read this. Thanks again Em!

**Comment by QuiteAFancyEmerald** [comment]
@SkidFace Look under the Tab Cloak section in Options menu. You can use this to disguise your tab. (This is already a thing lol and has been a thing for a very long time)
![image](https://user-images.githubusercontent.com/46467239/110398882-a37fac80-8029-11eb-8542-5d4059810ee6.png)

**Comment by QuiteAFancyEmerald** [comment]
Going to close this since this is kind of invalid whoops
Feel free to comment still though.

**Comment by defcon277** [comment]
Does it work for everything or only some stuff

**Comment by the-skiddo** [comment]
@defcon277 , It worked on almost any site I tried. If it doesn't work, try another method. I suggest using Alloy or Womginx first, then Unblocker.

**Comment by defcon277** [comment]
Thanks!
