### ISSUE TITLE
youtubeproxy page (yt.html) not work on mobile devices

### ISSUE THREAD

**Issue by kakamband** [QuiteAFancyEmerald/InvisiProxy#3]
Hi TheEmeraldStarr,
youtubeproxy page (yt.html) not work on mobile devices
waiting for your changes
finest regards

**Comment by QuiteAFancyEmerald** [comment]
I'll try to work on that. I wonder if it ever worked on mobile. Try using Alloy and going to https://m.youtube.com instead.

**Comment by kakamband** [comment]
can you make static html page for mobile devices using alloy ?
it's better than type any time youtube mobile address
finest regards

**Comment by QuiteAFancyEmerald** [comment]
Will work on that. I'll comment back when I get this done. Give me like maybe four days? Maybe less. :)

**Comment by QuiteAFancyEmerald** [comment]
Alright should be fixed?
