### ISSUE TITLE
Need help with selfhosting

### ISSUE THREAD

**Issue by morg-mov** [QuiteAFancyEmerald/InvisiProxy#31]
I'm trying to set up the website to run on a Freenom domain connected to Cloudflare proxied thru Nginx.
Everything works except for the ones that utilize subdomains.
Here are pictures of my Nginx Proxy Manager config and Cloudflare DNS Records.

Basic Config:
![image](https://user-images.githubusercontent.com/56270390/110965367-1cc91900-8322-11eb-860c-bf9b0ce6727d.png)

SSH Config:
![image](https://user-images.githubusercontent.com/56270390/110965696-6dd90d00-8322-11eb-9e6e-f0e53970b989.png)
Force SSL, HTTP/2 Support, and HSTS are enabled.

Cloudflare DNS Records:
![image](https://user-images.githubusercontent.com/56270390/110965982-cc9e8680-8322-11eb-887b-4c5faf97de4d.png)

And you can also check it out for yourself: [https://unblocked44.ml](https://unblocked44.ml).

Any help would be appreciated. Thanks!

**Comment by QuiteAFancyEmerald** [comment]
Everything seems to be setup correctly. :D

Just note that the only proxy that is hosted locally with this distribution of Holy Unblocker is Alloy. Every other proxy would either need to be hosted on another instance or you could proxy pass it locally on a subdomain with NGINX.

**Here are the links to the various proxies which you may need:**
https://github.com/binary-person/womginx (Womginx)
https://github.com/titaniumnetwork-dev/alloy (Alloy Proxy if you wish for an updated version)
https://github.com/sysce/proxy (SysYA Proxy)
https://github.com/BinBashBanana/PyDodge (Via/PyDodge)

Also note that the only real subdomains you will need are _a_ (Womginx), _c_ (SysYA Proxy), _cdn_ (Updated, external Alloy Proxy), _c_ but you might want to change it to something like _p_ (Via/PyDodge). 

Most of these are just things I forgot to mention in the README lol oops

**Comment by morg-mov** [comment]
It's no problem, thanks so much for the help!
I'll give it a try when I get home.

Edit: Sorry for all the unnecessary reply info. I was on my phone and I used E-Mail to reply and Github pulled my response along with the reply info that Google Puts into E-Mails lol

**Comment by QuiteAFancyEmerald** [comment]
Oh don't worry about it! :D 
And of course no problem.

**Comment by defcon277** [comment]
Thanks, I'll check it out.   
  
  
  
  
  
    
  

  
  
>

**Comment by QuiteAFancyEmerald** [comment]
Going to close this issue since it's been a long while now. I did some changes to the README related to setup information though if that helps. :)
