### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by irhrhd** [QuiteAFancyEmerald/InvisiProxy#33]
When i try to use via on heroku or any other proxy than alloy it redirects me to a blocked site and says this site can not be reached

**Comment by QuiteAFancyEmerald** [comment]
Read over the README for detailed information regarding the below.

Taken from #31: 

"Just note that the only proxy that is hosted locally with this distribution of Holy Unblocker is Alloy. Every other proxy would either need to be hosted on another instance or you could proxy pass it locally on a subdomain with NGINX.

**Here are the links to the various proxies which you may need:**
https://github.com/binary-person/womginx (Womginx)
https://github.com/titaniumnetwork-dev/alloy (Alloy Proxy if you wish for an updated version)
https://github.com/sysce/proxy (SysYA Proxy)
https://github.com/BinBashBanana/PyDodge (Via/PyDodge)

Also note that the only real subdomains you will need are a (Womginx), c (SysYA Proxy), cdn (Updated, external Alloy Proxy), c but you might want to change it to something like p (Via/PyDodge)."
