### ISSUE TITLE
Help? its Flo. btw on discord Emerald

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/InvisiProxy#34]
So um i need help i use this for school sometimes and they recently blocked i cant go on to the comments where i first found it b/c they blocked it So what do i do

**Comment by QuiteAFancyEmerald** [comment]
And you haven't joined the Titanium Network discord on a personal device to request for another Holy Unblocker site?

**Comment by ghost** [comment]
i dont have a phone and the one i requested on discord when ur proxy wasnt blocked for me got blocked

**Comment by QuiteAFancyEmerald** [comment]
Well try this then. It's one of the links I posted on the review pages.

https://mathbot.xyz

**Comment by ghost** [comment]
Legend but they will block this in a month or so then we will have the same issue over again

**Comment by QuiteAFancyEmerald** [comment]
Yikes. As a suggestion you can perhaps try finding an online VM service of some sort. (Like Onworks) Maybe even something on like repl would work, where you would temporarily sign into Discord. Not secure at all and I don't really advise it but it would work.

Going to close this issue but feel free to make any comments.
