### ISSUE TITLE
Womginx has trouble with YouTube

### ISSUE THREAD

**Issue by SkidFace** [QuiteAFancyEmerald/InvisiProxy#35]
Hey Em! This is probably a known issue, but I'll say it anyways. Here's the problem: when using Womginx to access YouTube, a couple of issues occur. First off, it immediately locks the scroll to right where you can't see the video, and you cannot scroll back up or down (I think the youtube video's audio manages to play though). Secondly, almost nothing renders on the page except the default grey spots where elements of the page(such as recommended videos, pfp's, etc.)  would have been. Thanks for reading!

**Comment by QuiteAFancyEmerald** [comment]
Yeah, Womginx doesn't have good support for YouTube. :(

I recommend looking into using Alloy proxy, which is currently the best proxy for YouTube support, following the FAQ information regarding YouTube use under any of the proxies.
