### ISSUE TITLE
Add Geforce Now Support [enhancement]

### ISSUE THREAD

**Issue by unrealapex** [QuiteAFancyEmerald/InvisiProxy#36]
Currently, trying to access Geforce Now with Holy Unblocker is not possible. When trying to log in, there is a redirect error. It would be nice to be able to use Geforce Now on less powerful work/school devices such as chromebooks.

**Comment by QuiteAFancyEmerald** [comment]
This would be a really unoptimized addition though, like imagine the lag. Perhaps such a thing could be possible in the future with any of the proxies used on Holy Unblocker but for now, this will be a "wontfix" moment.
