### ISSUE TITLE
Hey Emerald so um it happened again 

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/InvisiProxy#37]
Yes Emerald they blocked it again hu um i coming to u with the same problem and this is getting kind of annoying but uh yeah Help?

**Comment by unrealapex** [comment]
You can join the [Titanium Network discord](https://discord.gg/hcUUceSCtj) where new proxy sites while being restocked often, and you will have a wide selection between the different proxy sites while still unblocking various sites.
--
Type "%proxy hu" in the Titanium Network Discord for more private/unblocked Holy Unblocker sites! 
(a bot will DM you a site and are often restocked with new links and are not Freenom domains.)

**Comment by ghost** [comment]
I cant join it b/c i dont have a phone to verify my acc with and i cant join sorry and i know u guys cant share links so i need help

**Comment by unrealapex** [comment]
heres [a working one](https://recession.cf/)
----
You might get a redirect error, but reloading the page once should fix it.

**Comment by ghost** [comment]
it didnt work i reloaded it it just shows Connection timed out im trying multiple times but it isnt working

**Comment by unrealapex** [comment]
It appears the server is currently down.

**Comment by ghost** [comment]
oh ok then WELL THANK U SO MUCH APEX u legend i appreciate u

**Comment by QuiteAFancyEmerald** [comment]
Yeah, Holy Unblocker is down right now, working on it, though.

**Comment by ghost** [comment]
its ok
take ur time

**Comment by unrealapex** [comment]
> oh ok then WELL THANK U SO MUCH APEX u legend i appreciate u

I appreciate your sarcasm.

**Comment by ghost** [comment]
no im serious

**Comment by unrealapex** [comment]
Nevermind

**Comment by ghost** [comment]
thx anyway man l8r

**Comment by unrealapex** [comment]
@Floisasimp   On the [securly chrome web store page](https://chrome.google.com/webstore/detail/securly-for-chromebooks/iheobagjkfklnlikgihanlhcddjoihkg), new links are begin posted each day. Just go to the review tab, and there should be a review by @QuiteAFancyEmerald  that has been updated recently.
