### ISSUE TITLE
an Idea

### ISSUE THREAD

**Issue by ApoorKID** [QuiteAFancyEmerald/InvisiProxy#39]
You should leave a link to a google doc that has the links to the website on it and title the rating and fake acting like you have been defeated and leave the link with no context.

**Comment by ApoorKID** [comment]
sorry I have bad for English

**Comment by QuiteAFancyEmerald** [comment]
lol why though

**Comment by unrealapex** [comment]
> You should leave a link to a google doc that has the links to the website on it and title the rating and fake acting like you have been defeated and leave the link with no context.

It could work, wouldn't for users that had their google account admin block access to files from drive outside of their domain.

**Comment by ApoorKID** [comment]
I don't know I have a low iq

**Comment by ApoorKID** [comment]
Im sorry when waste your time

**Comment by QuiteAFancyEmerald** [comment]
oops its alright

**Comment by unrealapex** [comment]
@ApoorKID  Proposing ideas is not a waste of time by any means. By doing so, you are helping us. User feedback is valuable and is what helps us do things like create new features and fix bugs.

**Comment by ApoorKID** [comment]
ok I just figured that if they were blocking them by reading the links that you put on there

**Comment by unrealapex** [comment]
On the [securly chrome web store page](https://chrome.google.com/webstore/detail/securly-for-chromebooks/iheobagjkfklnlikgihanlhcddjoihkg), new links are begin posted each day. Just go to the review tab, and there should be a review by Fancy Emerald that has been updated recently.
