### ISSUE TITLE
[Beginners Tutorial] Finding more proxy site links + Learning how to create a proxy site

### ISSUE THREAD

**Issue by martyhil123** [QuiteAFancyEmerald/InvisiProxy#4]
The school provided me with a school chromebook. I just signed up for github looking for a means to unblock blocked websites on a school computer. I have used repl.it before, but only very vaugley. I wanted to message one of the developers but I didn't see a message button. So my question, How would I go about installing this on a chromebook? (Github was unblocked on my chromebook, maybe because they think kids are dumb and won't try and make there own way out) Please explain this for a beginner like myself. I already have made an account for heroku.

**Comment by martyhil123** [comment]
I might not check github often. please message me on twitter (@M1sterM3rty) or discord (Sp00ked#2264) if I do not message back within a few days.

**Comment by Rockpods** [comment]
I am not author but on heroku you should be able to use this link to make a Holy Unblocker site. https://heroku.com/deploy?template=https://github.com/QuiteAFancyEmerald/HolyUnblockerPublic  for repl.it use this link: https://repl.it/github/QuiteAFancyEmerald/HolyUnblockerPublic

**Comment by martyhil123** [comment]
Alright thanks, I don't want to make one I just want to get to the one the people made. Thank you, Rockpods.

**Comment by martyhil123** [comment]
worked on my school windows computer. Didn't work on the school chromebook. It took some time to load then it blocked it and gave the reason (school branch, block) for ex. BCPS Block. Looks like it wouldn't be as easy as I thought it would be. Any suggestions?

**Comment by QuiteAFancyEmerald** [comment]
I would not try developing this on your Chromebook but I do have some suggestions if I am interpreting your question correctly.

### If you are trying to access the complete updated site list join the Titanium Network discord as I update the lists often and you will find other similar sites to HB on it. :D 
https://discord.gg/Dw6C7p5
### If you are trying to make your own
**So use Heroku to host. I personally favor it as a free choice.** 
- Next get a card from here if you don't already have one or use your own. Either works but you need a credit card or prepaid card to add custom domains with Heroku. (https://www.paypal-prepaid.com/)
Make sure you connect your Heroku app to your GitHub and enable automatic deploys. Will make things easier. :) 
**Freenom Steps**
- Get some Freenom domains then add them to your Heroku instance (Personal > [App Name] > Settings > Domains)
Add a domain for both `www.youdomainhere.cf` and `yourdomainhere.cf` with .cf being interchangeable with other Freedom domain names.
**Cloudflare Steps**
- Use Cloudflare (make an account), add your site (Freenom Domain) and then add your various DNS targets to Cloudflare. 
**Make sure they are CNAME and try to follow this structure:**
==
**Type | Name | Target**
`CNAME | www | yourherokutargethere.herokudns.com `
`CNAME | @ | yourherokudnstargethere.herokudns.com`
**Below are if you want external proxies also with your site:**
`CNAME | a | yournodeinstance.herokudns.com`
`CNAME | pd | yourpydodgebinstancehere.herokudns.com`
`CNAME | p | yourpowermouseinstancehere.herokudns.com`
Make sure HTTPS is forced and have SSL set to Flexible.
==
For an online IDE that you can use on your school computer and/or chromebook use GitPod. Basically the equivalent of Visual Studio Code but with in-browser support.
- Make an account: `https://gitpod.io/`
- Fork this repo and enter in this URL to setup your workspace: `https://gitpod.io#https://github.com/YourNameHere/HolyUnblockerPublic/

Hopefully this helps.

**Comment by martyhil123** [comment]
Well, I made an account for Heroku and made my own app and everything and launched it and it worked. It only worked on my windows school issued computer. I tried doing the same thing for my brothers chromebook. But when I pressed launched it took some time to load and then said blocked. I think the whole county/district restricts one from launching apps on any unknown sites with strange mechanisms.  But I will check the discord out. Since they blocked discord as-well on the chromenbooks.. could you link a few sites that are unblocked currently? I want to be able to go on discord and watch crunchyroll.

**Comment by QuiteAFancyEmerald** [comment]
**Response:**
Sure! Um not sure about Crunchyroll working on any proxy but look at r/AnimePiracy for other sites that may work under a proxy. But Discord does work, with Alloy. So does YouTube. :)

**General Site List:**
https://deportedpencil.cf
https://cattttttttttttttttttttttttsss.cf/

**Comment by martyhil123** [comment]
Before I close this, are there any known anime sites that work using the unblocker? I tried the ones you listed and some sites loaded but the players for the anime title didn't work. any way to fix? (i cant access holy unblocker, when I click it says 'this website is dangerous! move back into safety!"

**Comment by QuiteAFancyEmerald** [comment]
@martyhil123 Like I said you will need to maybe join the TN discord for more links. Some of them are down right now or reported unfortunately. I am going to release a new list soon though. As for anime sites that work I am not too sure.

**Comment by martyhil123** [comment]
Both websites now got blocked. deported pencil is now considered as a security proxy and cats takes long time to load then just not work. could i get more sites please?

**Comment by QuiteAFancyEmerald** [comment]
DM me on Discord or join the server above please. I don't want to leak any sites here. 

Quite A Fancy Emerald#0001

**Comment by martyhil123** [comment]
ok.

**Comment by liamjgkelly** [comment]
you already did above
