### ISSUE TITLE
Alloy Doesnt Work 

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/InvisiProxy#46]
Alloy doesnt work it shows cookie is too big to process tried resetting and doing some other things but they never worked tried for support in chatbox no one responded

**Comment by QuiteAFancyEmerald** [comment]
If this occurs on the official sites, what site are you trying to access through Alloy? Not all sites are supported on Alloy, and occasionally certain sites which are not supported have this error.
