### ISSUE TITLE
Hey My school blocked one of ur sites 

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#48]
I wanted to use hu but i found out that my school blocked it is there anything i can do

**Comment by WeDoABitOfTrolling** [comment]
You could try to find another proxy site, or go to the official Titanium Network discord server and do “%proxy HU” for another proxy site (the discord link is in the README)

**Comment by QuiteAFancyEmerald** [comment]
^

**Comment by Susdevlmao** [comment]
i tried to do that but i dont have a phone and discord locked me out of my account when i made my account
