### ISSUE TITLE
holy unblocker blocked

### ISSUE THREAD

**Issue by MrMachi9** [QuiteAFancyEmerald/InvisiProxy#49]
a.grammarfiles.net is blocked

**Comment by WeDoABitOfTrolling** [comment]
You could go to the discord server in the readme and do “%proxy HU” to get another proxy site, or you could try to find another proxy site by going into the closed issues.

**Comment by MrMachi9** [comment]
discord is blocked

**Comment by MrMachi9** [comment]
- [ ] 

1. 

- 

> _[](url)_

**Comment by QuiteAFancyEmerald** [comment]
Sorry, I can't really provide you another site here since it would be blocked pretty quickly. You can try looking on the review pages later this week when I post more disposable domains. I think on one of the issues here, I provided another site. It might be worth looking for it.

**Comment by MrMachi9** [comment]
actually all i need is  like 3 seconds cause i really wanna play krunker so maybe i can get the krunker site unblocked

**Comment by MrMachi9** [comment]
even if its just for one day

**Comment by MrMachi9** [comment]
ok
