### ISSUE TITLE
holy unblockers blocked

### ISSUE THREAD

**Issue by MrMachi9** [QuiteAFancyEmerald/InvisiProxy#51]
i really need help with this

**Comment by MrMachi9** [comment]
please comment back i need holy unblocker

**Comment by QuiteAFancyEmerald** [comment]
What filter do you have? I'll consider sharing a mirror here but just know that it will probably be blocked quickly. Also, read over what I said in the last issue.

**Comment by MrMachi9** [comment]
but can you send me a link to an unblocked krunker.io

**Comment by Cypherpix** [comment]
btw @QuiteAFancyEmerald i wont ask for another site if u give me a site if my school blocks it

**Comment by Cypherpix** [comment]
@MrMachi9 https://sites.google.com/view/yupiunblockedgames/krunker try this or this https://sites.google.com/view/frivgo/krunker or this https://funblocked.sites.google.com/site/allfunblockedgames/krunker-io

**Comment by MrMachi9** [comment]
there all blocked

**Comment by Cypherpix** [comment]
hmmm uh https://unblockedgames.sites.google.com/site/unblocked66world/krunker-io 
https://skribblio.club/io-games/krunker-io.html
https://tyrone.sites.google.com/site/tyronesgamesez/krunker-io 
any of these work?

**Comment by MrMachi9** [comment]
those are also blocked

**Comment by Cypherpix** [comment]
rip

**Comment by Cypherpix** [comment]
what hu link did u have before send it here

**Comment by MrMachi9** [comment]
what do you mean

**Comment by Cypherpix** [comment]
like what was the link of the holy unblocker that ur school blocked

**Comment by MrMachi9** [comment]
a.grammarfiles.net

**Comment by Cypherpix** [comment]
oh

**Comment by MrMachi9** [comment]
do you have krunker

**Comment by Cypherpix** [comment]
damn well uhh idk how to help u what blocker does ur school do

**Comment by MrMachi9** [comment]
securly

**Comment by ahyowinner** [comment]
> i really need help with this

me too

**Comment by ahyowinner** [comment]
and if you are making a new holy unblocker pls let the minecraft work so we can play with friends

**Comment by MrMachi9** [comment]
winner what you doin in this issue

**Comment by the-skiddo** [comment]
Ah yes, we have Securly too. It's not as easy as using a separate link for Krunker. Krunker and all of the other proxies haven't gotten along too well recently, so I suggest you just wait it out until there's a fix. If you want to make your own bypass for Krunker, try to make your own website and put this into the body of it: 

<iframe src="https://krunker.io"></iframe>

It's a little laggy, but is a good thing to use until fixed.

**Comment by QuiteAFancyEmerald** [comment]
Please quit asking for more Holy Unblocker links if you can't join the Discord and request for more sites through the proxy bot or don't have another device. Just wait until I post them on the review pages, to those who are asking. So many duplicate "issues."
