### ISSUE TITLE
i tried to do that but i dont have a phone and discord locked me out of my account when i made my account

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#52]
i tried to do that but i dont have a phone and discord locked me out of my account when i made my account

_Originally posted by @Cypherpix in https://github.com/QuiteAFancyEmerald/Holy-Unblocker/issues/48#issuecomment-815308921_

**Comment by Susdevlmao** [comment]
so i need something else i cant use discord so what can i do

**Comment by QuiteAFancyEmerald** [comment]
Read over #49 or #51 later.

**Comment by QuiteAFancyEmerald** [comment]
Please quit asking for more Holy Unblocker links if you can't join the Discord and request for more sites through the proxy bot or don't have another device. Just wait until I post them on the review pages, to those who are asking. So many duplicate "issues."
