### ISSUE TITLE
HOLY UNBLOCKER

### ISSUE THREAD

**Issue by ahyowinner** [QuiteAFancyEmerald/InvisiProxy#55]
how do i get holy unblocker

**Comment by the-skiddo** [comment]
Go to one of their sites, such as https://flexibleedu.gq/

Next time, don't say the same question.

**Comment by ahyowinner** [comment]
thank you btw

**Comment by ahyowinner** [comment]
is there a way you could get me minecraft that you can beat and can do with friends and if you can't do both do one

**Comment by the-skiddo** [comment]
No, it's for browser only. Also, if you use Chromebook (which I assume you are since you are in school) Minecraft is very hard to run.

**Comment by ahyowinner** [comment]
ok 1 last thing in holy unblocker venge.io it will not put me in a match

**Comment by the-skiddo** [comment]
It probably uses  recaptia, and none of the proxies support it. I think one will be made soon though.

**Comment by ahyowinner** [comment]
can you tell me when it does

**Comment by the-skiddo** [comment]
Possibly, but I assume that Em will close this question soon, so I can't respond. I think you can find out if he has by just checking if he says it on this repository.

**Comment by ahyowinner** [comment]
can i come back incase i lose the holy unblocker i have

**Comment by the-skiddo** [comment]
If you are at home, you can go to their discord: https://discord.com/invite/hcUUceSCtj 

Go to #proxy-commands and type: %proxy hu

It should give you a fresh link.

**Comment by QuiteAFancyEmerald** [comment]
Please quit asking for more Holy Unblocker links if you can't join the Discord and request for more sites through the proxy bot or don't have another device. Just wait until I post them on the review pages, to those who are asking. So many duplicate "issues." D:

**Comment by the-skiddo** [comment]
yep :(

**Comment by easella** [comment]
venge io works if u use alloyproxy  on repl.co
[click here](http://partialvirtualredundancy-1.awdrgyjil1234.repl.co/)
