### ISSUE TITLE
Krunker dosent work

### ISSUE THREAD

**Issue by MrMachi9** [QuiteAFancyEmerald/InvisiProxy#56]
i cant get krunker.io

**Comment by MrMachi9** [comment]
can i please get krunker

**Comment by the-skiddo** [comment]
It's not as easy as using a separate link for Krunker. Krunker and all of the other proxies haven't gotten along too well recently, so I suggest you just wait it out until there's a fix. If you want to make your own bypass for Krunker, try to make your own website and put this into the body of it:

<iframe src="https://krunker.io"></iframe>


It's a little laggy, but is a good thing to use until fixed.

**Comment by QuiteAFancyEmerald** [comment]
#24
