### ISSUE TITLE
Better support for minecraft java 

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#57]
Im asking if u could uh support the minecraft java in ur game tab in hu just a thought

**Comment by the-skiddo** [comment]
Yeah, that's impossible. Minecraft (both Java and Bedrock) are application-based games, and it would be impossible to have it work in a chrome tab. Even if it did work,  I assume you are on Chromebook, which would have lag that is unplayable. Really nothing you can do to get Minecraft on a chromebook.

**Comment by QuiteAFancyEmerald** [comment]
I thought that was obvious :(

**Comment by QuiteAFancyEmerald** [comment]
Don't keep opening tiny brain "suggestions" or "issues". Hmm, well you could use a Remote Desktop service like Dixper if the site is unblocked for you but that really isn't a reliable solution. You would also need another device for it.

Dixper:  https://remote-play.dixper.gg/rooms
