### ISSUE TITLE
SystemYA Proxy Has Problems. 

### ISSUE THREAD

**Issue by SkidFace** [QuiteAFancyEmerald/InvisiProxy#58]
Hey there! You probably don't have control over this since VibeDivide runs this proxy, but upon searching anything using SysYa, it returns this error: 

Error at GET /prox

upstream returned 502

connection lasted for -

I just wanted to point it out if you are able to fix it. Thanks!

**Comment by QuiteAFancyEmerald** [comment]
How long has this been an issue? This issue is most likely temporary since Divide might be working on the proxy instance, plus this issue also occurs on the SystemYA proxy sites.

So wait a bit :)

**Comment by the-skiddo** [comment]
Ah, got it. Thanks :D

**Comment by QuiteAFancyEmerald** [comment]
Issue should be fixed :D

**Comment by SkidFace** [comment]
Thanks man, works like a charm again :)
