### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by ASchoolUser** [QuiteAFancyEmerald/InvisiProxy#6]
Our school blocked the site for "Not allowed to browse **Newly Registered Domains** category". If you can, can you fix that issue so that we can use the site? 

Thanks,
ASchoolUser

**Comment by QuiteAFancyEmerald** [comment]
I'm sorry yikes I can't get around that. However you can use this old site that might be unblocked for now. I think you will need to wait until it gets unblocked... wow huh.

Try this.. hope it works: https://usatextbook.cf

**Comment by QuiteAFancyEmerald** [comment]
I would also suggest joining the Titanium Network discord for older but likely to be unblocked domains which are updated often.

https://discord.gg/Dw6C7p5
