### ISSUE TITLE
Alloy Proxy

### ISSUE THREAD

**Issue by TheLegacyofTron** [QuiteAFancyEmerald/InvisiProxy#60]
Can you Make it so reCAPTCHA Supports Alloy, because I use it for Discord but it has a ReCAPTCHA For it and I can't use Womginx because it doesn't work for me when I try it.

**Comment by QuiteAFancyEmerald** [comment]
I don't maintain Alloy lol (there is an issue already related to this on the official Alloy repo)

Also, Womginx does have reCAPTCHA support, it's just rather buggy and it takes a few attempts. By few attempts I mean it will eventually work afterawhile.

**Comment by TheLegacyofTron** [comment]
Ok Thank you!

**Comment by QuiteAFancyEmerald** [comment]
ofc np :D
