### ISSUE TITLE
vibeos not working

### ISSUE THREAD

**Issue by abbabaa** [QuiteAFancyEmerald/InvisiProxy#62]
hey, when i go to the vibe os it doesnt show
 the mouse

**Comment by QuiteAFancyEmerald** [comment]
VibeOS Legacy is incredibly old and is no longer really maintained. Zooming out may help though.

Sorry :(

**Comment by Nebelung-Dev** [comment]
here is the code if it helps https://github.com/vibeOS/vibeos-legacy
