### ISSUE TITLE
Fix sitemap.xml

### ISSUE THREAD

**Issue by Nebelung-Dev** [QuiteAFancyEmerald/InvisiProxy#66]
It's broken

**Comment by the-skiddo** [comment]
Do you mean sitemap.xml?

**Comment by Nebelung-Dev** [comment]
ya sorry!

**Comment by QuiteAFancyEmerald** [comment]
Um, what do you mean by it being "broken"?

**Comment by Nebelung-Dev** [comment]
some of the links are broken

**Comment by Nebelung-Dev** [comment]
of the these links give a 404
some are probably in use
https://holyubofficial.net/?dd
https://holyubofficial.net/?ym
https://holyubofficial.net/?yh
https://holyubofficial.net/?k
https://holyubofficial.net/?n

**Comment by QuiteAFancyEmerald** [comment]
I accidentally added this though, haven't bothered to update it since it was an unintentional addition. Will remove it soon since yeah.. make your own sitemap lol
