### ISSUE TITLE
Marked as Dangerous

### ISSUE THREAD

**Issue by Cooliokid956** [QuiteAFancyEmerald/InvisiProxy#7]

**Comment by Cooliokid956** [comment]
one of the links, the deportedpencil one

**Comment by QuiteAFancyEmerald** [comment]
Yeah it is. In the meantime try the below.

**Updated Link:** https://particlefrank.cf/
**TN Discord:** https://discord.gg/Dw6C7p5
**My Discord if you wish to DM about it:** Quite A Fancy Emerald#0001

I would also suggest joining the TN discord for updated links and more proxy sites.
