### ISSUE TITLE
Unblock every day

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#73]
PLZ unblock this site every day, it gets blocked very fast in my district.

**Comment by QuiteAFancyEmerald** [comment]
I try to post new sites on the review pages but are you in the TN discord yet? (There are a lot of similar issues here relating to this...)

TN Discord: https://discord.com/invite/hcUUceSCtj

Simply type "%proxy hu" and the bot will DM you a new site link (one that won't get blocked that quickly.) 
All the domains I post on the review pages are meant to be disposable.
