### ISSUE TITLE
Game Request: Full Geometry Dash

### ISSUE THREAD

**Issue by Nebelung-Dev** [QuiteAFancyEmerald/InvisiProxy#76]
The is multiple parts
https://scratch.mit.edu/projects/105500895/
https://scratch.mit.edu/projects/105500895/
https://scratch.mit.edu/projects/120721851/
https://scratch.mit.edu/projects/140185501/
https://scratch.mit.edu/projects/194164289/
https://scratch.mit.edu/projects/194895616/

**Comment by the-skiddo** [comment]
I wouldn't use scratch to code geometry dash. I would use Unity to make it, but I don't think you should be asking him to make a full-fledged geometry dash game. Maybe you could try to make it and export it as WebGL which would allow it to be unblocked online automatically.

**Comment by Nebelung-Dev** [comment]
https://sheeptester.github.io/htmlifier/

**Comment by Nebelung-Dev** [comment]
it makes a single html file for the game

**Comment by Nebelung-Dev** [comment]
levels 1-3 are from scratch on hu

**Comment by easella** [comment]
here is the html game:[click here](https://lavishbruisedfiber.awdrgyjil1234.repl.co/s.html)

**Comment by Nebelung-Dev** [comment]
it would be hosted locally

**Comment by Pers0n-dev** [comment]
@easella use my chat
Chat: https://discord.gg/Y3RNdJYwPn
Titan: https://titanembeds.com/embed/833754408080506920
Chatutils: https://personchat.herokuapp.com

**Comment by easella** [comment]
ok.

**Comment by easella** [comment]
I love it!

**Comment by easella** [comment]
by the way what filter does your school have?

**Comment by easella** [comment]
can you also provide me more holy unblocker links?
my schools blocks incog.dev,holyubofficial.net,holyubofficial.ml, beachball.xyz,referencefile.org,and grammarfiles.net
make sure it ends in .gov, .dev,.com,.org, .co, or .edu
Almost all urls that do not end in that are blocked

**Comment by easella** [comment]
by the way can you provide the source code for your chat app(the heroku one)

**Comment by easella** [comment]
[click here](https://WearableExtrasmallListener#index.html) to view the source code

**Comment by Pers0n-dev** [comment]
Its very complacated

**Comment by Nebelung-Dev** [comment]
You need discord unblocked and there is a lot of setup. Just use this https://github.com/uxrkhan/chatrooms

**Comment by the-skiddo** [comment]
If you are at home, you can go to their discord: https://discord.com/invite/hcUUceSCtj

Go to #proxy-commands and type: %proxy hu

It should give you a fresh link.

**Comment by easella** [comment]
but I like your chat better

**Comment by Pers0n-dev** [comment]
the chat is really hard to set up and requires you to be the server owner or admin

**Comment by easella** [comment]
what do you mean?

**Comment by Pers0n-dev** [comment]
it is connected to discord

**Comment by easella** [comment]
oh

**Comment by Pers0n-dev** [comment]
https://github.com/titaniumnetwork-dev/chatutils

**Comment by easella** [comment]
so you mean I have to be the owner of a discord server to set up the chat?

**Comment by Pers0n-dev** [comment]
ya

**Comment by easella** [comment]
can you provide me with more systemya links? that end in .gov, .net,.co,.inc,.com,.org,or .edu?

**Comment by Pers0n-dev** [comment]
all hu site have system ya

**Comment by easella** [comment]
they are all blocked

**Comment by Pers0n-dev** [comment]
https://consolidateedu.xyz

**Comment by easella** [comment]
blocked

**Comment by Pers0n-dev** [comment]
if you want a chat use this https://github.com/uxrkhan/chatrooms

**Comment by easella** [comment]
any more systemya links

**Comment by Pers0n-dev** [comment]
no

**Comment by easella** [comment]
please?

**Comment by Pers0n-dev** [comment]
ask divide or someone

**Comment by easella** [comment]
what do u mean?

**Comment by Pers0n-dev** [comment]
ask someone else

**Comment by easella** [comment]
who is divide?

**Comment by Pers0n-dev** [comment]
https://github.com/vibedivide

**Comment by easella** [comment]
and by the way voidnet doesnt work

**Comment by Pers0n-dev** [comment]
its old

**Comment by easella** [comment]
can u make it work?

**Comment by Pers0n-dev** [comment]
use ludicrous

**Comment by easella** [comment]
tell me the link

**Comment by Pers0n-dev** [comment]
https://ludicrous-dev.herokuapp.com/

**Comment by easella** [comment]
doesnt work
![image](https://user-images.githubusercontent.com/74786054/115913713-f3320000-a43e-11eb-89df-19de6d889a5c.png)

**Comment by Pers0n-dev** [comment]
http://releasetime.ga/

**Comment by easella** [comment]
blocked

**Comment by Nebelung-Dev** [comment]
lets not chat here 
use chat https://personchat.herokuapp.com/

**Comment by easella** [comment]
ok

**Comment by easella** [comment]
how do you create a custom avatar?

**Comment by easella** [comment]
I did and he said join the discord but i dont have my own phone

**Comment by Pers0n-dev** [comment]
use zoom method?

**Comment by QuiteAFancyEmerald** [comment]
Goodness, why so spammy. :(

I'll consider updating the Geometry Dash (Scratch Edition) on Holy Unblocker later.

**Comment by QuiteAFancyEmerald** [comment]
Should be updated now
