### ISSUE TITLE
Game Request: Syobon Action 

### ISSUE THREAD

**Issue by Nebelung-Dev** [QuiteAFancyEmerald/InvisiProxy#77]
https://github.com/int3/open-syobon-action.js/tree/gh-pages

**Comment by QuiteAFancyEmerald** [comment]
Perhaps, I'll look into it.

**Comment by Nebelung-Dev** [comment]
cool its just 2 files

**Comment by MrMachi9** [comment]
hmm

**Comment by MrMachi9** [comment]
interesting

**Comment by Brady-Shike** [comment]
add it

**Comment by Susdevlmao** [comment]
smh why is this still open

**Comment by Nebelung-Dev** [comment]
cuz

**Comment by vackyton** [comment]
hmmm

**Comment by easella** [comment]
Hey everyone I made a service(https://historybooks.awdrgyjil1234.repl.co) that has a bunch of holyunblocker urls, Lucridious Official(very similar to holy unblocker, has womginx, alloy, and pydodge) urls, systemya urls, nodeunblocker urls, and alloyproxy urls! It has a password. Contact me at my email easella@yahoo.com and I will tell you the password.

**Comment by Nebelung-Dev** [comment]
you don't have to add it though

**Comment by QuiteAFancyEmerald** [comment]
bruh

**Comment by Nebelung-Dev** [comment]
ok :D
