### ISSUE TITLE
Game Request: 1v1 LOL

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#79]
PLZ AD THIS

**Comment by easella** [comment]
alloyproxy works with 1v1.lol

**Comment by Brady-Shike** [comment]
It's glitchy on proxy

**Comment by the-skiddo** [comment]
It already works well on Alloy. The game itself might be a little glitchy, so there's nothing Em can do for it.

**Comment by Nebelung-Dev** [comment]
system ya has it https://sys32.dev/gateway?url=MXYxLmxvbA%3D%3D

**Comment by QuiteAFancyEmerald** [comment]
I'll consider adding this to the games library. I say consider since well you can just use Alloy for this.
