### ISSUE TITLE
Authorization required. Go back to the main page. -Bot Protection-

### ISSUE THREAD

**Issue by kakamband** [QuiteAFancyEmerald/InvisiProxy#8]
after deployed to heroku & goin to browse youtube via top bar menu in all versions tell me :
Authorization required.
Go back to the main page.
-Bot Protection-
please help me to solve it 
https://holyunblockerpublic.herokuapp.com/?y
waiting for your response
finest regards

**Comment by QuiteAFancyEmerald** [comment]
Issue is fixed! (Changes on the master branch)

Sorry for the errors.
