### ISSUE TITLE
Game Request: Newgrounds

### ISSUE THREAD

**Issue by Brady-Shike** [QuiteAFancyEmerald/InvisiProxy#81]
Classic game

**Comment by the-skiddo** [comment]
Yeah NG is awesome, let me check real quick which proxy is best

**Comment by the-skiddo** [comment]
Alloy seems to ignore the website's CSS for some reason, but it does have SOME support

**Comment by easella** [comment]
pydodge works
[pydodge](https://maple-butter.herokuapp.com/course/https://www.newgrounds.com/)

**Comment by QuiteAFancyEmerald** [comment]
Epic, just to update on this I will be adding PyDodge B since it has decent support for a large majority of sites... also because Via is no longer being worked on.

**Comment by MrMachi9** [comment]
can i get krunker

**Comment by the-skiddo** [comment]
@MrMachi9 , check this out: #24 . Before you ask questions like that, I highly suggest you actually check other people's questions first.

**Comment by QuiteAFancyEmerald** [comment]
PyDodge is now featured on Holy Unblocker. :)

**Comment by the-skiddo** [comment]
> PyDodge is now featured on Holy Unblocker. :)

Very nice, thanks Em!
