### ISSUE TITLE
Issue with Hu

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#82]
Hey Emerald so when i use alloy on twitter it blocks it even though With other proxys it doesnt block but it goes to twitter for 1 second it just says blocked so i cant go on it

**Comment by Susdevlmao** [comment]
nvm

**Comment by Susdevlmao** [comment]
No it is a problem its not working for me

**Comment by Susdevlmao** [comment]
i need help

**Comment by easella** [comment]
works for me
