### ISSUE TITLE
Hu problem

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#83]
Hey Emerald so when i use alloy on twitter it blocks it even though With other proxys it doesnt block but it goes to twitter for 1 second it just says blocked so i cant go on it

**Comment by QuiteAFancyEmerald** [comment]
This is an odd issue with Alloy but try reloading the page or going to direct Twitter links, should work then unless something has changed.

**Comment by Susdevlmao** [comment]
its still blocked

**Comment by QuiteAFancyEmerald** [comment]
Only Alloy has Twitter support... what do you mean by blocked? Are you by chance using something like Womginx where occasionally links escape?

**Comment by Susdevlmao** [comment]
no im not alloy is what im talking about when i use the direct link to go to someone profile it says please reload and when i do it says blocked by securly firewall bam right there in my face

**Comment by easella** [comment]
works for me
[click here](https://partialvirtualredundancy-1.awdrgyjil1234.repl.co/web/_aHR0cHM6Ly90d2l0dGVyLmNvbQ==_/home)

**Comment by Susdevlmao** [comment]
whenever i use alloy it just says blocked

**Comment by easella** [comment]
well my school uses contentkeeper

**Comment by Susdevlmao** [comment]
also @QuiteAFancyEmerald discord on womginx doesnt work anymore

**Comment by Susdevlmao** [comment]
for me at least

**Comment by QuiteAFancyEmerald** [comment]
Try accessing Discord now on Womginx. Also maybe move this issue to the Alloy proxy repo. :)
