### ISSUE TITLE
Game Request: Ev.io

### ISSUE THREAD

**Issue by MrMachi9** [QuiteAFancyEmerald/InvisiProxy#85]
it used to be allowed on our school but its blocked

**Comment by easella** [comment]
heres the link:[click here](https://geometrypractice.glitch.me)

**Comment by easella** [comment]
does ur school use securely?

**Comment by MrMachi9** [comment]
yes

**Comment by easella** [comment]
so ur school uses securely

**Comment by MrMachi9** [comment]
yea

**Comment by easella** [comment]
then many games on my site will be blocked

**Comment by easella** [comment]
here is a proxy:[click here](womginx.synricha.org)

**Comment by QuiteAFancyEmerald** [comment]
If it doesn't work on any of the current proxies featured on HU then rip. Possible that it could be supported in the future though. :)
