### ISSUE TITLE
Can't join Discord

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/InvisiProxy#86]
Can you please put holy unblocker beside 
petty.gq 
grammarflies.net 
holyublockerofficial.net

**Comment by QuiteAFancyEmerald** [comment]
So many people have made similar issues... look on the webstore review pages for Securly or through past issues here. You might be able to find another site that way. Otherwise please don't ask.

**Comment by vackyton** [comment]
Sorry

**Comment by QuiteAFancyEmerald** [comment]
its alright :D
