### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by keevan163** [QuiteAFancyEmerald/InvisiProxy#88]
I am using the "deploy to Heroku" button on this github but when the build is finished and the app is deployed, I open up the heroku app in a different tab and it says: 

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

Here is the link to my heroku:  https://math-systems.herokuapp.com

_________________________
@QuiteAFancyEmerald

**Comment by keevan163** [comment]
I am new to the proxy and deployment stuff. Help would be greatly appreciated @QuiteAFancyEmerald

**Comment by QuiteAFancyEmerald** [comment]
I'll look into this. From the above, you seem to be doing everything correctly. :D

**Comment by QuiteAFancyEmerald** [comment]
Alright, this seems to be an issue with the latest update. Will resolve this as soon as I can.

**Comment by keevan163** [comment]
Thank you so much!!

**Comment by QuiteAFancyEmerald** [comment]
Issue should be fixed now :D
