### ISSUE TITLE
some changes on youtube proxies

### ISSUE THREAD

**Issue by kakamband** [QuiteAFancyEmerald/InvisiProxy#9]
Hi TheEmeraldStarr,
in my country some regular domains can load youtube important elements are censored , like ggpht.com , ytimg.com.
please fix this domains can also being obfuscate in holyunblocker pipes.
waiting for your response
finest regards

**Comment by QuiteAFancyEmerald** [comment]
The following may be considered as this issue would be more directly related to Alloy proxy which is hosted locally on Holy Unblocker.

Alloy Proxy GitHub: https://github.com/titaniumnetwork-dev/alloyproxy
