### ISSUE TITLE
Game Request: mini royale 2

### ISSUE THREAD

**Issue by ahyowinner** [QuiteAFancyEmerald/InvisiProxy#90]
pls add mini royale 2

**Comment by MrMachi9** [comment]
hi

**Comment by QuiteAFancyEmerald** [comment]
Can you perhaps link this?

**Comment by MrMachi9** [comment]
hes my brother my chrome wasnt working at the time so i told him to make the issue and i cant link this

**Comment by ahyowinner** [comment]
can we get mini royale

**Comment by QuiteAFancyEmerald** [comment]
Not possible if it isn't supported on any of the current proxies
