### ISSUE TITLE
CrunchyRoll Support

### ISSUE THREAD

**Issue by Susdevlmao** [QuiteAFancyEmerald/InvisiProxy#92]
Emerald........

Can u do it?

**Comment by the-skiddo** [comment]
Anime in class... **Hmmmmmm**

**Comment by Susdevlmao** [comment]
THIS GUY GETS IT

**Comment by QuiteAFancyEmerald** [comment]
Uhh, most likely not. Once again Holy Unblocker is a proxy site, not a proxy lol

Perhaps in the future it may be supported on a future proxy but it's unlikely

**Comment by Susdevlmao** [comment]
RIP :(
