### ISSUE TITLE
Discord proxy showing 404 error on all discord URLs

### ISSUE THREAD

**Issue by TeeNikx** [QuiteAFancyEmerald/InvisiProxy#93]
Not sure why it does this, but it wasn't happening yesterday, and today it was. 
![Screenshot 2021-05-02 at 9 00 31 PM](https://user-images.githubusercontent.com/65968350/116840079-7662fc80-ab89-11eb-91b2-281d48bb48ec.png)

**Comment by QuiteAFancyEmerald** [comment]
Does this issue occur on the official sites? Also, are you accessing Discord from the Discord proxy page?

**Comment by QuiteAFancyEmerald** [comment]
Looked into it, problem should be fixed now.
